git:
  depth: 3
  quiet: true
matrix:
  include:
    - os: linux
      sudo: required
      dist: trusty
      language: android
      compiler: clang
      android:
        components:
          - tools
          - build-tools
          - platform-tools
          - android-21
        licenses:
          - 'android-sdk-preview-license-.+'
          - 'android-sdk-license-.+'
          - 'google-gdk-license-.+'
      before_script:
        - sudo apt-get install ant libprotobuf-dev protobuf-compiler
        - echo yes | sdkmanager "ndk-bundle"
        - echo yes | sdkmanager "cmake;3.10.2.4988404"
        - export ANDROID_NDK=$ANDROID_HOME/ndk-bundle
        - export PATH=/usr/local/android-sdk/cmake/3.10.2.4988404/bin/:$PATH
      script:
        - ./ciscripts/Android/64.sh
        - ls -l ./project/android/build_64
      name: "Android | AArch64_ThreadPool_Vulkan"
      env:
        - MNNCITARGET=ARM64THREADPOOLVULKAN
